---
title: "VDOT ATSPM Dashboard TMC Segments Map"
author: "Kimley-Horn"
date: "Last Updated: January 2022"
# output: html_document
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: MARK1_Map.css

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressMessages({
    library(yaml)
    library(sp)
    library(leaflet)
    library(readxl)
    library(arrow)
    library(dplyr)
    library(tidyr)
    library(purrr)
    library(stringr)
    library(aws.s3)
    library(readr)
    library(htmltools)
    library(glue)
    library(forcats)
    library(qs)
    library(tictoc)
})

future::plan(future::multicore)


BLACK <- "#000000"
WHITE <- "#FFFFFF"
GRAY <- "#D0D0D0"
DARK_GRAY <- "#7A7A7A"
DARK_DARK_GRAY <- "#494949"

RED <- "#e41a1c"
BLUE <- "#005DAA" # VDOT Blue (previously: "#377eb8")
GREEN <- "#115740"  # W&M Official Orange  (previously: "#4daf4a")
PURPLE <- "#984ea3"
ORANGE <- "#E57200"  # UVA Official Orange  (previously: #ff7f00")
MAROON <- "#861F41"  # Va Tech Official Maroon
YELLOW <- "#ffff33"
BROWN <- "#a65628"
PINK <- "#f781bf"

LIGHT_RED <- "#f7babb"
LIGHT_BLUE <- "#b3dcff"  # "#c4dbed"
LIGHT_GREEN <- "#3fd9a7"  # "#cae8c9"
LIGHT_PURPLE <- "#e3cbe6"
LIGHT_ORANGE <- "#ffd9b3"
LIGHT_MAROON <- "#f1c1d1"
LIGHT_YELLOW <- "#ffffb3"
LIGHT_BROWN <- "#f0d2c1"
LIGHT_PINK <- "#fab7da"

conf <- read_yaml("Monthly_Report.yaml")

BUCKET <- conf$bucket

# --Copied over from Superbowl_UI_Functions.R -------------
points_to_line <- function(data, long, lat, id_field = NULL, sort_field = NULL) {
    
    # Convert to SpatialPointsDataFrame
    coordinates(data) <- c(long, lat)
    
    # If there is a sort field...
    if (!is.null(sort_field)) {
        if (!is.null(id_field)) {
            data <- data[order(data[[id_field]], data[[sort_field]]), ]
        } else {
            data <- data[order(data[[sort_field]]), ]
        }
    }
    
    # If there is only one path...
    if (is.null(id_field)) {
        
        lines <- SpatialLines(list(Lines(list(Line(data)), "id")))
        
        return(lines)
        
        # Now, if we have multiple lines...
    } else if (!is.null(id_field)) {  
        
        # Split into a list by ID field
        paths <- sp::split(data, data[[id_field]])
        
        sp_lines <- SpatialLines(list(Lines(list(Line(paths[[1]])), "line1")))
        
        if (length(paths) > 1) {
            # I like for loops, what can I say...
            for (p in 2:length(paths)) {
                id <- paste0("line", as.character(p))
                l <- SpatialLines(list(Lines(list(Line(paths[[p]])), id)))
                sp_lines <- spRbind(sp_lines, l)
            }
        }

        return(sp_lines)
    }
}
#----------------------------------------------------------
get_tmc_coords <- function(coords_string) {
    coord2 <- str_extract(coords_string, pattern = "(?<=')(.*?)(?=')")
    coord_list <- str_split(str_split(coord2, ",")[[1]], " ")
    
    tmc_coords <- purrr::transpose(coord_list) %>%
        lapply(unlist) %>%
        as.data.frame(., col.names = c("longitude", "latitude")) %>%
        mutate(latitude = as.numeric(trimws(latitude)),
               longitude = as.numeric(trimws(longitude)))
    as_tibble(tmc_coords)
}
#----------------------------------------------------------
get_geom_coords <- function(coords_string) {
    if (!is.na(coords_string)) {
            coord_list <- str_split(unique(str_split(coords_string, ",|:")[[1]]), " ")
    
    geom_coords <- purrr::transpose(coord_list) %>%
        lapply(unlist) %>%
        as.data.frame(., col.names = c("longitude", "latitude")) %>%
        mutate(latitude = as.numeric(trimws(latitude)),
               longitude = as.numeric(trimws(longitude)))
    as_tibble(geom_coords)
    }
}
#----------------------------------------------------------
```



```{r Corridors and Colors, echo=FALSE, eval=TRUE}

# --- Corridors Listing ---


# corridor_palette <- c()

corridors <- s3read_using(
    read_excel,
    bucket = BUCKET,
    object = conf$corridors_filename_s3)


num_corridors <- nrow(distinct(corridors))
zones <- distinct(corridors, Zone)

zone_colors <- zones %>%
    mutate(
        color = case_when(
            Zone == "Central Region" ~ RED, 
            Zone == "Eastern Region" ~ GREEN,
            Zone == "Fredericksburg District" ~ PINK,
            Zone == "Northern Region" ~ BLUE,
            Zone == "Southwest Region" ~ MAROON,
            Zone == "Northwest Region" ~ ORANGE,
            TRUE ~ DARK_GRAY),
        accent_color = case_when(
            Zone == "Central Region" ~ LIGHT_RED, 
            Zone == "Eastern Region" ~ LIGHT_GREEN,
            Zone == "Fredericksburg District" ~ LIGHT_PINK,
            Zone == "Northern Region" ~ LIGHT_BLUE,
            Zone == "Southwest Region" ~ LIGHT_MAROON,
            Zone == "Northwest Region" ~ LIGHT_ORANGE,
            TRUE ~ DARK_GRAY)
    )

corridor_colors <- corridors %>%
    select(Zone, Corridor) %>%
    left_join(zone_colors, by = "Zone")
```



```{r Intersections, echo=FALSE, eval=TRUE}

# --- Intersections (Point Layer) ---

ints <- filter(corridors, !is.na(Latitude), !is.na(Longitude))

signals_sp <- ints %>%
    mutate(
        Corridor = forcats::fct_explicit_na(Corridor, na_level = "None")) %>%
    left_join(zone_colors, by = c("Zone")
    ) %>%
    mutate(
        Description = paste0(SignalID, ": ", `Main Street Name`, " at ", `Side Street Name`)) %>%
    rename(
        fill_color = accent_color,
        stroke_color = color
    )

Encoding(signals_sp$Description) <- "utf-8"


statewide_signals_sp <- read_excel("VDOT_TrafficSignals_Export_2022-01-20.xlsx", skip = 4) %>%
    select(REG_SIGNAL, KITS_ID, MAJ_NAME, MINOR_NAME, DISTRICT, ATSPM, Latitude, Longitude)
```



```{r TMC Segments from s3 xlsx 2, echo=FALSE, eval=TRUE}
tmcs <- s3read_using(
    read_excel,
    bucket = BUCKET,
    object = conf$corridors_TMCs_filename_s3) %>%
    left_join(corridor_colors, by = c("Corridor")) %>%
    replace_na(list(color = GRAY)) %>%
    mutate(Zone = factor(Zone))
```



```{r Create SpatialDataFrame, echo=FALSE, eval=TRUE}
tic()
# -- This takes a little while
z <- tmcs %>% 
    filter(!is.na(Corridor)) %>% 
    mutate(
        tmc_coords = furrr::future_map(coordinates, get_tmc_coords),  # purrr::map
        sp_data = furrr::future_map(
            tmc_coords, function(y) {
                points_to_line(data = y, long = "longitude", lat = "latitude")
            })
        )

corridors_sp <- do.call(rbind, z$sp_data) %>%
    SpatialLinesDataFrame(z, match.ID = FALSE)


sz <- filter(z, !is.na(Subcorridor))

subcorridors_sp <- do.call(rbind, sz$sp_data) %>%
    SpatialLinesDataFrame(sz, match.ID = FALSE)


map_data <- list(
    corridors_sp = corridors_sp, 
    subcorridors_sp = subcorridors_sp, 
    signals_sp = signals_sp,
    statewide_signals_sp = statewide_signals_sp)
toc()
```



```{r, echo=FALSE, eval=FALSE}
# == Save locally and to S3 == ==
qsave(map_data, "map_data.qs")
put_object("map_data.qs",
           bucket = BUCKET,
           object = "map_data.qs",
           multipart = TRUE)
# s3write_using(qsave, 
#               map_data, 
#               bucket = BUCKET,
#               object = "map_data.qs")
# == == == ==
```



```{r Read Map Data, echo=FALSE, eval=FALSE}
map_data <- qread("map_data.qs")
```



```{r TMCs Map, echo=FALSE, fig.height=14, eval=TRUE}

#    and was updated on Monthly_Report_beta.Rmd on EC2 ----
line_popups <- function(num, name, corr, subc, tmc) {
    paste(sep = "<br/>", 
          glue("<b>Corridor: {corr}</b>"), 
          glue("<b>Subcorridor: {subc}</b>"), 
          glue("<b>Route Number:</b> {num}"),
          glue("<b>Road Name:</b> {name}"),
          glue("<b>TMC Code:</b> {tmc}"))
}

point_popups <- function(description, zone, corridor, subcorridor) {
    paste(sep = "<br/>", 
          glue("<b>Signal: {description}</b>"), 
          glue("<b>Zone:</b> {zone}"),
          glue("<b>Corridor:</b> {corridor}"),
          glue("<b>Subcorridor:</b> {subcorridor}"))
}

statewide_signals_popups <- function(sigid, kitsid, major_name, minor_name, district) {
    paste(sep = "<br/>", 
          glue("<b>Signal:</b> {sigid}"),
          glue("<b>KITS ID:</b> {kitsid}"),
          glue("<b>Location: {major_name} @ {minor_name}</b>"), 
          glue("<b>District:</b> {district}"))
}

line_labels <- function(zone, corridor, subcorridor, tmc) {
    paste(sep = " | ", 
          glue("Region: {zone}"),
          glue("Corridor: {corridor}"),
          glue("Subcorridor: {subcorridor}"),
          glue("TMC Code: {tmc}"))
}

map <- leaflet(width = "100%", height = 1000) %>% 
    setView(
        lat = 37.5247764, 
        lng = -77.5633012, 
        zoom = 10) %>%
    
    addProviderTiles(
        providers$CartoDB.Positron) %>% 
        addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
        addProviderTiles(providers$Esri.WorldTopoMap, group = "Topo") %>%
        addProviderTiles(providers$CartoDB.Positron, group = "Light") %>%
        addProviderTiles(providers$CartoDB.DarkMatter, group = "Dark") %>%
    
        addLayersControl(
            baseGroups = c("Light", "Dark","Satellite", "Topo"),
            overlayGroups = c("Statewide Signals"),
            options = layersControlOptions(collapsed = FALSE)
        ) %>%
    
    # TMC Segments with no Corridor assigned highlight as black on hover
    # addPolylines(
    #     data = subset(map_data$corridors_sp, is.na(Zone)),
    #     color = ~color,
    #     popup = ~line_popups(roadNumber, roadName, Corridor, Subcorridor, tmc),
    #     label = ~htmltools::htmlEscape(line_labels(Zone, Corridor, Subcorridor, tmc)),
    #     highlightOptions = highlightOptions(stroke = TRUE, color = BLACK, opacity = 1)) %>%

    # TMC Segments with Subcorridor assigned are thick and gray
    addPolylines(
        data = map_data$subcorridors_sp,
        color = GRAY, opacity = 1,
        popup = ~line_popups(roadNumber, roadName, Corridor, Subcorridor, tmc),
        label = ~line_labels(Zone, Corridor, Subcorridor, tmc),
        highlightOptions = highlightOptions(stroke = TRUE, color = BLACK, opacity = 1),
        weight = 20) %>%

    # TMC Segments with a Corridor assigned are colored by Zone
    addPolylines(
        data = subset(map_data$corridors_sp, !is.na(Zone)),
        color = ~color, opacity = 1,
        popup = ~line_popups(roadNumber, roadName, Corridor, Subcorridor, tmc),
        label = ~line_labels(Zone, Corridor, Subcorridor, tmc),
        highlightOptions = highlightOptions(stroke = TRUE, color = BLACK, opacity = 1)) %>%
    
    # Statewide Signals -- those not configured in the Dashboard corridors file
    addCircleMarkers(
        group = "Statewide Signals",
        data = map_data$statewide_signals_sp,
        lng = ~Longitude,
        lat = ~Latitude,
        popup = ~statewide_signals_popups(REG_SIGNAL, KITS_ID, MAJ_NAME, MINOR_NAME, DISTRICT),
        radius = 5,
        fillColor = WHITE,
        color = DARK_GRAY,
        fillOpacity = 1,
        opacity = 1,
        weight = 2) %>%

    # Signals configured in the Dashboard corridors file are colored by Zone
    addCircleMarkers(
        data = map_data$signals_sp,
        lng = ~Longitude,
        lat = ~Latitude,
        popup = ~point_popups(Description, Zone, Corridor, Subcorridor),
        label = ~Description,  # point_labels(Description, Zone, Corridor),
        radius = 5,
        fillColor = ~fill_color,  # ~fill_color,
        color = ~stroke_color,  # ~stroke_color,
        stroke = TRUE,
        fillOpacity = 1,
        opacity = 1,
        weight = 3)

s3write_using(map, qs::qsave, bucket = BUCKET, object = "VDOT_Corridors_Map.qs")

map
```


